# Mineria de Datos

## Primer Parcial


### Introduccion

#### Conceptos

**Mineria de Datos:**
Es el proceso de descubrir patrones, anomalías y correlaciones ocultas en grandes volúmenes de datos usando herramientas computacionales y técnicas avanzadas.

#### Ciencia de Datos

Help and Documentation in Python

In [1]:
# La funcion help nos muestra una documentacion breve de algun objeto en python
help(len)

Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.



In [3]:
miLista = [1, 2, 3] # Lista de numeros enteros
help(miLista)

Help on list object:

class list(object)
 |  list(iterable=(), /)
 |
 |  Built-in mutable sequence.
 |
 |  If no argument is given, the constructor creates a new empty list.
 |  The argument must be an iterable if specified.
 |
 |  Methods defined here:
 |
 |  __add__(self, value, /)
 |      Return self+value.
 |
 |  __contains__(self, key, /)
 |      Return bool(key in self).
 |
 |  __delitem__(self, key, /)
 |      Delete self[key].
 |
 |  __eq__(self, value, /)
 |      Return self==value.
 |
 |  __ge__(self, value, /)
 |      Return self>=value.
 |
 |  __getitem__(self, index, /)
 |      Return self[index].
 |
 |  __gt__(self, value, /)
 |      Return self>value.
 |
 |  __iadd__(self, value, /)
 |      Implement self+=value.
 |
 |  __imul__(self, value, /)
 |      Implement self*=value.
 |
 |  __init__(self, /, *args, **kwargs)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |
 |  __iter__(self, /)
 |      Implement iter(self).
 |
 |  __le__(self, value, /)
 

In [4]:
print(len(miLista))

3


In [5]:
def square(a):
    """Esto es un Docstring"""
    return a**2

In [7]:
help(square)

Help on function square in module __main__:

square(a)



In [8]:
square??

In [9]:
# Recorrer un arreglo y llamando a la funcion square
for i in miLista:
    print(square(i))

1
4
9


---
## IPython Magic Commands

In [1]:
%timeit L = [n ** 2 for n in range(1000)]
# timeit sirve para evaluar el desempeño de una expresion en cuanto a tiempo

53.1 μs ± 385 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [2]:
# Con doble porcentaje podemos evaluar el desempeño
# en cuanto tiempo de mas de una linea de codigo
%%timeit L = []
for n in range(1000):
   L.append(n ** 2)

67.9 μs ± 658 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


---
## IPython and Shell Commands


In [3]:
!ls

"ls" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.


In [4]:
!pwd

"pwd" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.


In [5]:
!echo "printing from the shell"

"printing from the shell"


In [6]:
contents = !ls

In [7]:
print(contents)

['"ls" no se reconoce como un comando interno o externo,', 'programa o archivo por lotes ejecutable.']


In [8]:
directory = !pwd

In [9]:
print(directory)

['"pwd" no se reconoce como un comando interno o externo,', 'programa o archivo por lotes ejecutable.']


In [10]:
type(directory)

IPython.utils.text.SList

In [11]:
!cd ..

In [13]:
%cd /content

[WinError 2] El sistema no puede encontrar el archivo especificado: '/content'
C:\Users\178396\PycharmProjects\mineria-de-datos-jupyter-notebook


## Understanding Data Types in Python

In [14]:
# importa numpy y renombrarlo
import numpy as np

In [15]:
np.array([1,4,5,9,6,7])

array([1, 4, 5, 9, 6, 7])

In [16]:
# al ingresar enteros y flotantees los convierte en flotante
np.array([1,4,5,9.1,6.3,7.5])

array([1. , 4. , 5. , 9.1, 6.3, 7.5])

In [17]:
np.array([1,2,3,4,5], dtype=int)

array([1, 2, 3, 4, 5])

In [19]:
np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

## Creating Arrays from Scratch