# Mineria de Datos

## Primer Parcial


### Introduccion

#### Conceptos

**Mineria de Datos:**
Es el proceso de descubrir patrones, anomalías y correlaciones ocultas en grandes volúmenes de datos usando herramientas computacionales y técnicas avanzadas.

#### Ciencia de Datos

Help and Documentation in Python

In [1]:
# La funcion help nos muestra una documentacion breve de algun objeto en python
help(len)

Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.



In [3]:
miLista = [1, 2, 3] # Lista de numeros enteros
help(miLista)

Help on list object:

class list(object)
 |  list(iterable=(), /)
 |
 |  Built-in mutable sequence.
 |
 |  If no argument is given, the constructor creates a new empty list.
 |  The argument must be an iterable if specified.
 |
 |  Methods defined here:
 |
 |  __add__(self, value, /)
 |      Return self+value.
 |
 |  __contains__(self, key, /)
 |      Return bool(key in self).
 |
 |  __delitem__(self, key, /)
 |      Delete self[key].
 |
 |  __eq__(self, value, /)
 |      Return self==value.
 |
 |  __ge__(self, value, /)
 |      Return self>=value.
 |
 |  __getitem__(self, index, /)
 |      Return self[index].
 |
 |  __gt__(self, value, /)
 |      Return self>value.
 |
 |  __iadd__(self, value, /)
 |      Implement self+=value.
 |
 |  __imul__(self, value, /)
 |      Implement self*=value.
 |
 |  __init__(self, /, *args, **kwargs)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |
 |  __iter__(self, /)
 |      Implement iter(self).
 |
 |  __le__(self, value, /)
 

In [4]:
print(len(miLista))

3


In [5]:
def square(a):
    """Esto es un Docstring"""
    return a**2

In [7]:
help(square)

Help on function square in module __main__:

square(a)



In [8]:
square??

In [9]:
# Recorrer un arreglo y llamando a la funcion square
for i in miLista:
    print(square(i))

1
4
9


---
## IPython Magic Commands

In [3]:
%timeit L = [n ** 2 for n in range(1000)]
# timeit sirve para evaluar el desempeño de una expresion en cuanto a tiempo

54.3 μs ± 782 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [41]:
# Con doble porcentaje podemos evaluar el desempeño
# en cuanto tiempo de mas de una linea de codigo
%%timeit L = []
L = []
for n in range(1000):
   L.append(n ** 2)

UsageError: Line magic function `%%timeit` not found.


---
## IPython and Shell Commands


In [3]:
!ls

"ls" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.


In [4]:
!pwd

"pwd" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.


In [5]:
!echo "printing from the shell"

"printing from the shell"


In [6]:
contents = !ls

In [7]:
print(contents)

['"ls" no se reconoce como un comando interno o externo,', 'programa o archivo por lotes ejecutable.']


In [8]:
directory = !pwd

In [9]:
print(directory)

['"pwd" no se reconoce como un comando interno o externo,', 'programa o archivo por lotes ejecutable.']


In [10]:
type(directory)

IPython.utils.text.SList

In [11]:
!cd ..

In [13]:
%cd /content

[WinError 2] El sistema no puede encontrar el archivo especificado: '/content'
C:\Users\178396\PycharmProjects\mineria-de-datos-jupyter-notebook


## Understanding Data Types in Python

In [1]:
# importa numpy y renombrarlo
import numpy as np

In [15]:
np.array([1,4,5,9,6,7])

array([1, 4, 5, 9, 6, 7])

In [16]:
# al ingresar enteros y flotantees los convierte en flotante
np.array([1,4,5,9.1,6.3,7.5])

array([1. , 4. , 5. , 9.1, 6.3, 7.5])

In [17]:
np.array([1,2,3,4,5], dtype=int)

array([1, 2, 3, 4, 5])

In [19]:
np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

## Creating Arrays from Scratch

In [5]:
import numpy as np

In [7]:
np.zeros(
    10, # Cantidad de numeros de array
    dtype=int # Tipo de datos
)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
np.ones(
    (3,5), # Numeros de Renglones y Columnas
    dtype=int # De tipo entero
)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [9]:
np.full(
    (3, 5), # Tupla de Renglo y Columna
    3.14 # Numero a insertar en la Matriz
)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [11]:
np.arange(
    0, # donde inicia
    20, # Donde acaba
    2 # Salto de dos en dos
)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [13]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [14]:
# Crea un array de 3x3 de numero aleatorios entre 0 y 1
np.random.random((3, 3))

array([[0.95367169, 0.98856736, 0.82579366],
       [0.8693131 , 0.37958442, 0.30456565],
       [0.88190689, 0.30181958, 0.19696343]])

In [16]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[-1.01362822,  0.08064644,  1.61370071],
       [-0.89701378, -1.16000678,  0.88355177],
       [-0.67351145, -1.11556942, -1.52670926]])

In [17]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

array([[5, 7, 6],
       [6, 1, 6],
       [9, 2, 6]], dtype=int32)

In [18]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that memory location
np.empty(3)

array([1., 1., 1.])

In [22]:
np.random.randint(0, 6, (3, 3)) # Valores del 0 al 5 de 3x3

array([[1, 2, 1],
       [2, 1, 2],
       [0, 0, 3]], dtype=int32)

---
## The Basics of NumPy Arrays

### NumPy Array Attributes

In [23]:
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

In [24]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [25]:
x1

array([5, 0, 3, 3, 7, 9], dtype=int32)

In [26]:
x1[0]

np.int32(5)

In [27]:
x1[1]

np.int32(0)

In [28]:
x1[2]

np.int32(3)

In [29]:
x1[-2]

np.int32(7)

In [31]:
# Direccionammiento de matrices
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]], dtype=int32)

In [32]:
x2[0, 2]

np.int32(2)

In [34]:
x2[2, 3] # Numero de renglon y numero de Columna

np.int32(7)

---
# 📊 Análisis Estadístico Básico con NumPy

## Media (Mean)

In [35]:
data = np.array([1, 2, 3, 4, 5])
media = np.mean(data)
print(media)

3.0


## Promedio (Average) y Promedio Ponderado

In [36]:
data = np.array([1, 2, 3, 4, 5])
weights = np.array([1, 2, 3, 4, 5])
promedio = np.average(data)
promedio_ponderado = np.average(data, weights=weights)

In [40]:
print(f"Promedio: {promedio} y Promedio Ponderado: {promedio_ponderado}")

Promedio: 3.0 y Promedio Ponderado: 3.6666666666666665


## Mediana

In [42]:
mediana = np.median(data)
print(media)

3.0


## Varianza y Desviación Estándar

In [43]:
varianza = np.var(data)
desviacion = np.std(data)
print(f"Varianza: {varianza}, Desviacion: {desviacion}")

Varianza: 2.0, Desviacion: 1.4142135623730951


---
## Generación de Datos Aleatorios

In [44]:
muestra = np.random.normal(
    0, # Media de 0
    1, # Desviacion estandar
    1000 # Cantidad de Datos
)
print(np.mean(muestra), np.std(muestra))

-0.006543456960417206 1.0059985778093545


---
## Correlación

In [47]:
corr = np.corrcoef([1,2,3], [1,5,7])
print(corr)

[[1.         0.98198051]
 [0.98198051 1.        ]]


---
# Datos Estadisticos

In [10]:
import pandas as pd
from io import StringIO

In [11]:
raw = """Marca temporal\tNúmero de matrícula\t¿Cuántos años cumplidos tienes?\t¿Has realizado programas utilizando Python?\t¿Has utilizado Google Colab?\t¿Tienes cuenta de GitHub?
19/01/2026 18:32:18\t178920\t22\tSi\tNo\tSi
19/01/2026 18:32:23\t182712\t21\tSi\tNo\tSi
19/01/2026 18:32:25\t180370\t26\tSi\tSi\tSi
19/01/2026 18:32:27\t182570\t21\tSi\tSi\tSi
19/01/2026 18:32:28\t177622\t24\tSi\tNo\tSi
19/01/2026 18:32:29\t175166\t22\tSi\tSi\tSi
19/01/2026 18:32:30\t177573\t22\tSi\tSi\tSi
19/01/2026 18:32:35\t178430\t21\tSi\tSi\tSi
19/01/2026 18:32:38\t179169\t23\tSi\tNo\tSi
19/01/2026 18:32:41\t177263\t22\tSi\tSi\tSi
19/01/2026 18:32:48\t179884\t23\tSi\tNo\tSi
19/01/2026 18:32:48\t183016\t22\tSi\tNo\tSi
19/01/2026 18:32:50\t179033\t23\tSi\tSi\tNo
19/01/2026 18:32:54\t178218\t22\tSi\tNo\tSi
19/01/2026 18:32:55\t178446\t22\tSi\tSi\tSi
19/01/2026 18:33:00\t178166\t22\tSi\tSi\tNo
19/01/2026 18:33:02\t177406\t22\tSi\tNo\tSi
19/01/2026 18:33:05\t177192\t22\tSi\tSi\tSi
19/01/2026 18:33:08\t182451\t21\tSi\tNo\tSi
19/01/2026 18:33:08\t171513\t24\tNo\tNo\tSi
19/01/2026 18:33:09\t181619\t21\tSi\tNo\tSi
19/01/2026 18:33:12\t182298\t23\tSi\tNo\tSi
19/01/2026 18:33:14\t181419\t24\tNo\tNo\tSi
19/01/2026 18:33:32\t177291\t21\tSi\tSi\tSi
19/01/2026 18:33:42\t182085\t22\tSi\tNo\tSi
19/01/2026 18:33:53\t176453\t22\tSi\tNo\tSi
19/01/2026 18:34:04\t176263\t24\tSi\tNo\tSi
19/01/2026 18:34:06\t179997\t21\tSi\tNo\tSi
19/01/2026 18:36:21\t175842\t23\tSi\tNo\tNo
19/01/2026 20:19:21\t179913\t20\tSi\tNo\tSi
19/01/2026 20:19:48\t177301\t22\tSi\tSi\tNo
19/01/2026 20:20:06\t183060\t21\tSi\tNo\tSi
19/01/2026 20:20:08\t177935\t22\tSi\tSi\tSi
19/01/2026 20:20:19\t177700\t20\tSi\tSi\tSi
19/01/2026 20:20:26\t178318\t24\tSi\tSi\tSi
19/01/2026 20:20:27\t174653\t24\tSi\tNo\tSi
19/01/2026 20:20:29\t177139\t21\tSi\tNo\tSi
19/01/2026 20:20:31\t173479\t25\tSi\tNo\tNo
19/01/2026 20:20:39\t175588\t23\tNo\tNo\tSi
19/01/2026 20:20:45\t178774\t23\tSi\tSi\tSi
19/01/2026 20:20:45\t175031\t23\tSi\tNo\tNo
19/01/2026 20:20:49\t178396\t21\tSi\tSi\tSi
19/01/2026 20:20:49\t172068\t23\tNo\tNo\tNo
19/01/2026 20:20:50\t174197\t23\tNo\tNo\tSi
19/01/2026 20:20:55\t178584\t22\tSi\tNo\tSi
19/01/2026 20:20:55\t175329\t24\tSi\tNo\tSi
19/01/2026 20:20:56\t177685\t22\tSi\tSi\tSi
19/01/2026 20:20:57\t178678\t22\tNo\tNo\tSi
19/01/2026 20:21:04\t177143\t22\tSi\tNo\tSi
19/01/2026 20:21:07\t182318\t26\tSi\tNo\tSi
19/01/2026 20:21:27\t182377\t20\tSi\tNo\tSi
19/01/2026 20:21:34\t179419\t22\tSi\tNo\tNo
19/01/2026 20:21:35\t181662\t21\tSi\tNo\tSi
19/01/2026 20:21:38\t181760\t21\tSi\tNo\tSi
19/01/2026 20:22:06\t177888\t22\tSi\tNo\tSi
19/01/2026 20:22:15\t176535\t25\tSi\tNo\tSi
19/01/2026 20:22:29\t179862\t21\tSi\tNo\tSi
19/01/2026 20:22:32\t178378\t22\tSi\tNo\tSi
19/01/2026 20:22:50\t177451\t22\tSi\tNo\tSi
19/01/2026 20:23:15\t179804\t21\tSi\tNo\tSi
"""

In [12]:
# Cargar datos
df = pd.read_csv(StringIO(raw), sep='\t')
df.columns = [c.strip() for c in df.columns]

In [13]:
# Variables
df['edad'] = pd.to_numeric(df['¿Cuántos años cumplidos tienes?'], errors='coerce')
map_sn = {'Si': True, 'No': False}
df['prog_python'] = df['¿Has realizado programas utilizando Python?'].map(map_sn)
df['usa_colab'] = df['¿Has utilizado Google Colab?'].map(map_sn)
df['cuenta_github'] = df['¿Tienes cuenta de GitHub?'].map(map_sn)

In [14]:
df.head(5)

Marca temporal  Número de matrícula  ¿Cuántos años cumplidos tienes?  \
0  19/01/2026 18:32:18               178920                               22   
1  19/01/2026 18:32:23               182712                               21   
2  19/01/2026 18:32:25               180370                               26   
3  19/01/2026 18:32:27               182570                               21   
4  19/01/2026 18:32:28               177622                               24   

  ¿Has realizado programas utilizando Python? ¿Has utilizado Google Colab?  \
0                                          Si                           No   
1                                          Si                           No   
2                                          Si                           Si   
3                                          Si                           Si   
4                                          Si                           No   

  ¿Tienes cuenta de GitHub?  edad  prog_python  usa_colab  cuenta_github  
0                        Si    22         True      False           True  
1                        Si    21         True      False           True  
2                        Si    26         True       True           True  
3                        Si    21         True       True           True  
4                        Si    24         True      False           True

In [15]:
df.tail(5)

Marca temporal  Número de matrícula  ¿Cuántos años cumplidos tienes?  \
55  19/01/2026 20:22:15               176535                               25   
56  19/01/2026 20:22:29               179862                               21   
57  19/01/2026 20:22:32               178378                               22   
58  19/01/2026 20:22:50               177451                               22   
59  19/01/2026 20:23:15               179804                               21   

   ¿Has realizado programas utilizando Python? ¿Has utilizado Google Colab?  \
55                                          Si                           No   
56                                          Si                           No   
57                                          Si                           No   
58                                          Si                           No   
59                                          Si                           No   

   ¿Tienes cuenta de GitHub?  edad  prog_python  usa_colab  cuenta_github  
55                        Si    25         True      False           True  
56                        Si    21         True      False           True  
57                        Si    22         True      False           True  
58                        Si    22         True      False           True  
59                        Si    21         True      False           True

In [16]:
# A NumPy
edad = df['edad'].to_numpy(dtype=float)
prog_py = df['prog_python'].to_numpy(dtype=bool)
usa_colab = df['usa_colab'].to_numpy(dtype=bool)
cuenta_gh = df['cuenta_github'].to_numpy(dtype=bool)

In [20]:
print(f"ndarray edad de los primeros 5 elementos: {edad[:5]}")
print(f"ndarray prog_py primeros 5 elementos: {prog_py[:5]}")
print(f"ndarray usa_colab primeros 5 elementos {usa_colab[:5]}")
print(f"ndarray cuenta_gh primeros 5 elementos {cuenta_gh[:5]}")

ndarray edad de los primeros 5 elementos: [22. 21. 26. 21. 24.]
ndarray prog_py primeros 5 elementos: [ True  True  True  True  True]
ndarray usa_colab primeros 5 elementos [False False  True  True False]
ndarray cuenta_gh primeros 5 elementos [ True  True  True  True  True]


In [17]:
# Descriptivos de edad (NumPy)
summary_age = {
    'n': int(edad.size),
    'min': float(np.min(edad)),
    'p25': float(np.percentile(edad, 25)),
    'mediana': float(np.median(edad)),
    'media': float(np.mean(edad)),
    'p75': float(np.percentile(edad, 75)),
    'max': float(np.max(edad)),
    'rango(ptp)': float(np.ptp(edad)),
    'var_muestral': float(np.var(edad, ddof=1)),
    'std_muestral': float(np.std(edad, ddof=1)),
    'cv': float(np.std(edad, ddof=1)/np.mean(edad)),
}

In [33]:
import json
df = pd.json_normalize(summary_age)
df

n   min   p25  mediana  media   p75   max  rango(ptp)  var_muestral  \
0  60  20.0  21.0     22.0   22.3  23.0  26.0         6.0      1.840678   

   std_muestral        cv  
0      1.356716  0.060839

In [18]:
# Frecuencias (NumPy)
freq_python = {'Si': int(np.count_nonzero(prog_py)), 'No': int(edad.size - np.count_nonzero(prog_py))}
freq_colab  = {'Si': int(np.count_nonzero(usa_colab)), 'No': int(edad.size - np.count_nonzero(usa_colab))}
freq_gh     = {'Si': int(np.count_nonzero(cuenta_gh)), 'No': int(edad.size - np.count_nonzero(cuenta_gh))}

In [25]:
print(f"Frecuencias de utilizar Python: {freq_python}")
print(f"Frecuencias de utilizar Colab: {freq_colab}")
print(f"Frecuencias de utilizar GitHub: {freq_gh}")

Frecuencias de utilizar Python: {'Si': 54, 'No': 6}
Frecuencias de utilizar Colab: {'Si': 18, 'No': 42}
Frecuencias de utilizar GitHub: {'Si': 52, 'No': 8}


In [30]:
# Tablas cruzadas (NumPy)
def tabla2x2(a, b):
    t = np.zeros((2,2), dtype=int)
    t[1,1] = np.count_nonzero(a & b)
    t[1,0] = np.count_nonzero(a & ~b)
    t[0,1] = np.count_nonzero(~a & b)
    t[0,0] = np.count_nonzero(~a & ~b)
    return t

In [31]:
tab_py_colab = tabla2x2(prog_py, usa_colab)
tab_py_gh    = tabla2x2(prog_py, cuenta_gh)
tab_colab_gh = tabla2x2(usa_colab, cuenta_gh)

In [32]:
print(f"Tabla cruzada entre Python y Colab: {tab_py_colab}")
print(f"Tabla cruzada entre Python y GitHub: {tab_py_gh}")
print(f"Tabla cruzada entre Colab y GitHub: {tab_colab_gh}")

Tabla cruzada entre Python y Colab: [[ 6  0]
 [36 18]]
Tabla cruzada entre Python y GitHub: [[ 1  5]
 [ 7 47]]
Tabla cruzada entre Colab y GitHub: [[ 5 37]
 [ 3 15]]


In [36]:
# Medias de edad por grupo (NumPy)
means_by_group = {
    'edad_promedio_Python': {'Si': float(np.mean(edad[prog_py])) if np.any(prog_py) else np.nan,
                             'No': float(np.mean(edad[~prog_py])) if np.any(~prog_py) else np.nan},
    'edad_promedio_Colab':  {'Si': float(np.mean(edad[usa_colab])) if np.any(usa_colab) else np.nan,
                             'No': float(np.mean(edad[~usa_colab])) if np.any(~usa_colab) else np.nan},
    'edad_promedio_GitHub': {'Si': float(np.mean(edad[cuenta_gh])) if np.any(cuenta_gh) else np.nan,
                             'No': float(np.mean(edad[~cuenta_gh])) if np.any(~cuenta_gh) else np.nan},
}

In [37]:
summary_age, freq_python, freq_colab, freq_gh, tab_py_colab, tab_py_gh, tab_colab_gh, means_by_group

({'n': 60,
  'min': 20.0,
  'p25': 21.0,
  'mediana': 22.0,
  'media': 22.3,
  'p75': 23.0,
  'max': 26.0,
  'rango(ptp)': 6.0,
  'var_muestral': 1.8406779661016948,
  'std_muestral': 1.3567158752302173,
  'cv': 0.06083927691615324},
 {'Si': 54, 'No': 6},
 {'Si': 18, 'No': 42},
 {'Si': 52, 'No': 8},
 array([[ 6,  0],
        [36, 18]]),
 array([[ 1,  5],
        [ 7, 47]]),
 array([[ 5, 37],
        [ 3, 15]]),
 {'edad_promedio_Python': {'Si': 22.203703703703702, 'No': 23.166666666666668},
  'edad_promedio_Colab': {'Si': 22.11111111111111, 'No': 22.38095238095238},
  'edad_promedio_GitHub': {'Si': 22.21153846153846, 'No': 22.875}})

In [39]:
# Cargar Datos de un CSV
df = pd.read_csv("src/raw.csv")
df.columns = [c.strip() for c in df.columns]

In [40]:
# Variables
df['edad'] = pd.to_numeric(df['¿Cuántos años cumplidos tienes?'], errors='coerce')
map_sn = {'Si': True, 'No': False}
df['prog_python'] = df['¿Has realizado programas utilizando Python?'].map(map_sn)
df['usa_colab'] = df['¿Has utilizado Google Colab?'].map(map_sn)
df['cuenta_github'] = df['¿Tienes cuenta de GitHub?'].map(map_sn)

In [41]:
df.head(5)

Marca temporal  Número de matrícula  ¿Cuántos años cumplidos tienes?  \
0  19/01/2026 18:32:18               178920                               22   
1  19/01/2026 18:32:23               182712                               21   
2  19/01/2026 18:32:25               180370                               26   
3  19/01/2026 18:32:27               182570                               21   
4  19/01/2026 18:32:28               177622                               24   

  ¿Has realizado programas utilizando Python? ¿Has utilizado Google Colab?  \
0                                          Si                           No   
1                                          Si                           No   
2                                          Si                           Si   
3                                          Si                           Si   
4                                          Si                           No   

  ¿Tienes cuenta de GitHub?  edad  prog_python  usa_colab  cuenta_github  
0                        Si    22         True      False           True  
1                        Si    21         True      False           True  
2                        Si    26         True       True           True  
3                        Si    21         True       True           True  
4                        Si    24         True      False           True