# Mineria de Datos

## Primer Parcial


### Introduccion

#### Conceptos

**Mineria de Datos:**
Es el proceso de descubrir patrones, anomalías y correlaciones ocultas en grandes volúmenes de datos usando herramientas computacionales y técnicas avanzadas.

#### Ciencia de Datos

Help and Documentation in Python

In [1]:
# La funcion help nos muestra una documentacion breve de algun objeto en python
help(len)

Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.



In [3]:
miLista = [1, 2, 3] # Lista de numeros enteros
help(miLista)

Help on list object:

class list(object)
 |  list(iterable=(), /)
 |
 |  Built-in mutable sequence.
 |
 |  If no argument is given, the constructor creates a new empty list.
 |  The argument must be an iterable if specified.
 |
 |  Methods defined here:
 |
 |  __add__(self, value, /)
 |      Return self+value.
 |
 |  __contains__(self, key, /)
 |      Return bool(key in self).
 |
 |  __delitem__(self, key, /)
 |      Delete self[key].
 |
 |  __eq__(self, value, /)
 |      Return self==value.
 |
 |  __ge__(self, value, /)
 |      Return self>=value.
 |
 |  __getitem__(self, index, /)
 |      Return self[index].
 |
 |  __gt__(self, value, /)
 |      Return self>value.
 |
 |  __iadd__(self, value, /)
 |      Implement self+=value.
 |
 |  __imul__(self, value, /)
 |      Implement self*=value.
 |
 |  __init__(self, /, *args, **kwargs)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |
 |  __iter__(self, /)
 |      Implement iter(self).
 |
 |  __le__(self, value, /)
 

In [4]:
print(len(miLista))

3


In [5]:
def square(a):
    """Esto es un Docstring"""
    return a**2

In [7]:
help(square)

Help on function square in module __main__:

square(a)



In [8]:
square??

In [9]:
# Recorrer un arreglo y llamando a la funcion square
for i in miLista:
    print(square(i))

1
4
9


---
## IPython Magic Commands

In [3]:
%timeit L = [n ** 2 for n in range(1000)]
# timeit sirve para evaluar el desempeño de una expresion en cuanto a tiempo

54.3 μs ± 782 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [41]:
# Con doble porcentaje podemos evaluar el desempeño
# en cuanto tiempo de mas de una linea de codigo
%%timeit L = []
L = []
for n in range(1000):
   L.append(n ** 2)

UsageError: Line magic function `%%timeit` not found.


---
## IPython and Shell Commands


In [3]:
!ls

"ls" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.


In [4]:
!pwd

"pwd" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.


In [5]:
!echo "printing from the shell"

"printing from the shell"


In [6]:
contents = !ls

In [7]:
print(contents)

['"ls" no se reconoce como un comando interno o externo,', 'programa o archivo por lotes ejecutable.']


In [8]:
directory = !pwd

In [9]:
print(directory)

['"pwd" no se reconoce como un comando interno o externo,', 'programa o archivo por lotes ejecutable.']


In [10]:
type(directory)

IPython.utils.text.SList

In [11]:
!cd ..

In [13]:
%cd /content

[WinError 2] El sistema no puede encontrar el archivo especificado: '/content'
C:\Users\178396\PycharmProjects\mineria-de-datos-jupyter-notebook


## Understanding Data Types in Python

In [1]:
# importa numpy y renombrarlo
import numpy as np

In [15]:
np.array([1,4,5,9,6,7])

array([1, 4, 5, 9, 6, 7])

In [16]:
# al ingresar enteros y flotantees los convierte en flotante
np.array([1,4,5,9.1,6.3,7.5])

array([1. , 4. , 5. , 9.1, 6.3, 7.5])

In [17]:
np.array([1,2,3,4,5], dtype=int)

array([1, 2, 3, 4, 5])

In [19]:
np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

## Creating Arrays from Scratch

In [5]:
import numpy as np

In [7]:
np.zeros(
    10, # Cantidad de numeros de array
    dtype=int # Tipo de datos
)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
np.ones(
    (3,5), # Numeros de Renglones y Columnas
    dtype=int # De tipo entero
)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [9]:
np.full(
    (3, 5), # Tupla de Renglo y Columna
    3.14 # Numero a insertar en la Matriz
)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [11]:
np.arange(
    0, # donde inicia
    20, # Donde acaba
    2 # Salto de dos en dos
)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [13]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [14]:
# Crea un array de 3x3 de numero aleatorios entre 0 y 1
np.random.random((3, 3))

array([[0.95367169, 0.98856736, 0.82579366],
       [0.8693131 , 0.37958442, 0.30456565],
       [0.88190689, 0.30181958, 0.19696343]])

In [16]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[-1.01362822,  0.08064644,  1.61370071],
       [-0.89701378, -1.16000678,  0.88355177],
       [-0.67351145, -1.11556942, -1.52670926]])

In [17]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

array([[5, 7, 6],
       [6, 1, 6],
       [9, 2, 6]], dtype=int32)

In [18]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that memory location
np.empty(3)

array([1., 1., 1.])

In [22]:
np.random.randint(0, 6, (3, 3)) # Valores del 0 al 5 de 3x3

array([[1, 2, 1],
       [2, 1, 2],
       [0, 0, 3]], dtype=int32)

---
## The Basics of NumPy Arrays

### NumPy Array Attributes

In [23]:
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

In [24]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [25]:
x1

array([5, 0, 3, 3, 7, 9], dtype=int32)

In [26]:
x1[0]

np.int32(5)

In [27]:
x1[1]

np.int32(0)

In [28]:
x1[2]

np.int32(3)

In [29]:
x1[-2]

np.int32(7)

In [31]:
# Direccionammiento de matrices
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]], dtype=int32)

In [32]:
x2[0, 2]

np.int32(2)

In [34]:
x2[2, 3] # Numero de renglon y numero de Columna

np.int32(7)

---
# 📊 Análisis Estadístico Básico con NumPy

## Media (Mean)

In [35]:
data = np.array([1, 2, 3, 4, 5])
media = np.mean(data)
print(media)

3.0


## Promedio (Average) y Promedio Ponderado

In [36]:
data = np.array([1, 2, 3, 4, 5])
weights = np.array([1, 2, 3, 4, 5])
promedio = np.average(data)
promedio_ponderado = np.average(data, weights=weights)

In [40]:
print(f"Promedio: {promedio} y Promedio Ponderado: {promedio_ponderado}")

Promedio: 3.0 y Promedio Ponderado: 3.6666666666666665


## Mediana

In [42]:
mediana = np.median(data)
print(media)

3.0


## Varianza y Desviación Estándar

In [43]:
varianza = np.var(data)
desviacion = np.std(data)
print(f"Varianza: {varianza}, Desviacion: {desviacion}")

Varianza: 2.0, Desviacion: 1.4142135623730951


---
# Generación de Datos Aleatorios

In [44]:
muestra = np.random.normal(
    0, # Media de 0
    1, # Desviacion estandar
    1000 # Cantidad de Datos
)
print(np.mean(muestra), np.std(muestra))

-0.006543456960417206 1.0059985778093545


---
# Correlación

In [47]:
corr = np.corrcoef([1,2,3], [1,5,7])
print(corr)

[[1.         0.98198051]
 [0.98198051 1.        ]]
